<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.24">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>eda--baseline-model-info</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="EDA &amp; Baseline Model Info_files/libs/clipboard/clipboard.min.js"></script>
<script src="EDA &amp; Baseline Model Info_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="EDA &amp; Baseline Model Info_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="EDA &amp; Baseline Model Info_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="EDA &amp; Baseline Model Info_files/libs/quarto-html/popper.min.js"></script>
<script src="EDA &amp; Baseline Model Info_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="EDA &amp; Baseline Model Info_files/libs/quarto-html/anchor.min.js"></script>
<link href="EDA &amp; Baseline Model Info_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="EDA &amp; Baseline Model Info_files/libs/quarto-html/quarto-syntax-highlighting-dc55a5b9e770e841cd82e46aadbfb9b0.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="EDA &amp; Baseline Model Info_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="EDA &amp; Baseline Model Info_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="EDA &amp; Baseline Model Info_files/libs/bootstrap/bootstrap-9e3ffae467580fdb927a41352e75a2e0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">




<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode yaml code-with-copy"><code class="sourceCode yaml"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="pp">---</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">title</span><span class="kw">:</span><span class="at"> </span><span class="st">"Machine Learning Team Project:EDA"</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">author</span><span class="kw">:</span><span class="at"> </span><span class="st">"Colyn Martin, Ayushi Bohra, Matthew Fernald, and Mike Haynes"</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">date</span><span class="kw">:</span><span class="at"> </span><span class="st">"`r format(Sys.time(), '%d %B %Y')`"</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">number-sections</span><span class="kw">:</span><span class="at"> </span><span class="ch">true</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">number-depth</span><span class="kw">:</span><span class="at"> </span><span class="dv">3</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">format</span><span class="kw">:</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="at">  </span><span class="fu">html</span><span class="kw">:</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="at">    </span><span class="fu">toc</span><span class="kw">:</span><span class="at"> </span><span class="ch">true</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="at">    </span><span class="fu">toc-location</span><span class="kw">:</span><span class="at"> right</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="at">    </span><span class="fu">number-sections</span><span class="kw">:</span><span class="at"> </span><span class="ch">false</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="at">    </span><span class="fu">number-depth</span><span class="kw">:</span><span class="at"> </span><span class="dv">3</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="at">    </span><span class="fu">html-math-method</span><span class="kw">:</span><span class="at"> katex</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="at">    </span><span class="fu">embed-resources</span><span class="kw">:</span><span class="at"> </span><span class="ch">true</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="at">    </span><span class="fu">self-contained</span><span class="kw">:</span><span class="at"> </span><span class="ch">true</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a><span class="fu">execute</span><span class="kw">:</span></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a><span class="at">  </span><span class="fu">echo</span><span class="kw">:</span><span class="at"> </span><span class="ch">true</span></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a><span class="at">  </span><span class="fu">warning</span><span class="kw">:</span><span class="at"> </span><span class="ch">false</span></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a><span class="at">  </span><span class="fu">message</span><span class="kw">:</span><span class="at"> </span><span class="ch">false</span></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a><span class="at">  </span><span class="fu">cache</span><span class="kw">:</span><span class="at"> </span><span class="ch">false</span></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a><span class="fu">engine</span><span class="kw">:</span><span class="at"> knitr</span></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a><span class="pp">---</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<hr>
<section id="exploratory-data-analysis-eda" class="level1">
<h1>Exploratory Data Analysis (EDA)</h1>
<section id="project-overview" class="level2">
<h2 class="anchored" data-anchor-id="project-overview">1. Project Overview</h2>
<p>We used two groups of datasets: <strong>public_cases</strong> and <strong>private_cases</strong>, each containing various information such as trip duration (days), miles traveled, and total receipts (amount).<br>
The goal of this EDA is to evaluate the data quality, identify patterns, and prepare features for our machine learning model.</p>
</section>
<section id="data-used" class="level2">
<h2 class="anchored" data-anchor-id="data-used">2. Data Used</h2>
<p><strong>Datasets:</strong></p>
<p><code>public_cases</code> : 1000 rows x 4 columns</p>
<p>(<a href="https://github.com/MHaynes33/BlackBox/blob/main/data/public_cases.json">available at https://github.com/MHaynes33/BlackBox/blob/main/data/public_cases.json</a>).</p>
<p><code>private_cases</code> : 5000 rows x 3 columns</p>
<p>(<a href="https://github.com/MHaynes33/BlackBox/blob/main/data/private_cases.json">available at https://github.com/MHaynes33/BlackBox/blob/main/data/private_cases.json</a>).</p>
<p>~ note: rows are the instances and columns are: trip_duration_days, miles_traveled, total_receipts_amount, and expected_output (reimbursement). Both datasets have trip_duration_days, miles_traveled, and total_receipts_amount for columns but only <code>public_cases</code> has expected_output.</p>
<section id="dataset-features" class="level3">
<h3 class="anchored" data-anchor-id="dataset-features">Dataset Features</h3>
<p><strong>Features_of_Data_from_Public_Cases</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Description</th>
<th>Type</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>trip_duration_days</td>
<td>Duration of the trip in days</td>
<td>int64 (Numeric)</td>
</tr>
<tr class="even">
<td>miles_traveled</td>
<td>Total distance covered in miles</td>
<td>float64 (Numeric)</td>
</tr>
<tr class="odd">
<td>total_receipts_amount</td>
<td>Total trip cost in receipts</td>
<td>float64 (Numeric)</td>
</tr>
<tr class="even">
<td>expected_output</td>
<td>Model target variable (predicted or reference outcome)</td>
<td>float64 (Numeric)</td>
</tr>
</tbody>
</table>
<p><strong>Features_of_Data_from_Private_Cases</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 30%">
<col style="width: 43%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Description</th>
<th>Type</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>trip_duration_days</td>
<td>Duration of the trip in days</td>
<td>int64 (Numeric)</td>
</tr>
<tr class="even">
<td>miles_traveled</td>
<td>Total distance covered in miles</td>
<td>float64 (Numeric)</td>
</tr>
<tr class="odd">
<td>total_receipts_amount</td>
<td>Total trip cost in receipts</td>
<td>float64 (Numeric)</td>
</tr>
</tbody>
</table>
</section>
<section id="quality-check" class="level3">
<h3 class="anchored" data-anchor-id="quality-check">Quality Check</h3>
<p><strong>Assesing Missing Values</strong></p>
<p>The number of missing values for each individual variable as presented within each dataset was computed to assess data completeness.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Variable</th>
<th>Missing Values</th>
<th>% Missing</th>
<th>Comment</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>trip_duration_days</td>
<td>0</td>
<td>0%</td>
<td>Complete</td>
</tr>
<tr class="even">
<td>miles_traveled</td>
<td>0</td>
<td>0%</td>
<td>Complete</td>
</tr>
<tr class="odd">
<td>total_receipts_amount</td>
<td>0</td>
<td>0%</td>
<td>Complete</td>
</tr>
<tr class="even">
<td>expected_output</td>
<td>0</td>
<td>0%</td>
<td>Complete</td>
</tr>
</tbody>
</table>
<p><strong>Interpretation:</strong> No missing values were found in any column across both datasets (<code>public_cases</code> and <code>private_cases</code>).<br>
All variables show <strong>100% completeness</strong>, indicating no imputation or deletion is required beyond verification.</p>
<p><strong>Assessing Missing Values Once Data from Public Cases and Private Cases were Merged, so total should be 6000</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Missing Values</th>
<th>% Missing</th>
<th>Comment</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>trip_duration_days</td>
<td>0</td>
<td>0%</td>
<td>Complete</td>
</tr>
<tr class="even">
<td>miles_traveled</td>
<td>0</td>
<td>0%</td>
<td>Complete</td>
</tr>
<tr class="odd">
<td>total_receipts_amount</td>
<td>0</td>
<td>0%</td>
<td>Complete</td>
</tr>
<tr class="even">
<td>reimbursement (expected_output)</td>
<td>5000</td>
<td>83.3%</td>
<td>Mostly missing (because expected_output column is not available for <code>private_cases</code>, needs to predict eventually )</td>
</tr>
</tbody>
</table>
<dl>
<dt><strong>Interpretation:</strong> No missing values were found in any column across both datasets (<code>public_cases</code> and <code>private_cases</code>). However, there is a mismatched on total count within each feature since <code>private_cases</code> only had 3 columns instead of 4 and it does not have an expected_output column. However, this is an output that we are supposed to be able to predict.</dt>
<dd>
<p>Note: The expected_output column is relabeled reimbursement once we combined the data for both datasets (<code>public_cases</code> and <code>private_cases</code>)</p>
</dd>
<dt><strong>Assesing Range Validation</strong></dt>
<dd>
<p>Range validation helps ensures that each numeric variable contains values within logical and domain-appropriate limits.</p>
</dd>
</dl>
<p>For this dataset:</p>
<ul>
<li><p><strong>trip_duration_days (1–14):</strong> All trip durations are within a reasonable range, with no negative or unrealistic values.</p></li>
<li><p><strong>miles_traveled (5–1317):</strong> Distances are all positive and plausible for travel data, showing no errors or outliers.</p></li>
<li><p><strong>total_receipts_amount (1.42–2503.46):</strong> All costs are within a logical spending range, indicating consistent data entry, non were negative.</p></li>
<li><p><strong>expected_output (117.24–2337.73):</strong> Target values are realistic and proportional to trip and cost metrics, non were negative.</p></li>
</ul>
<p>No range violations were identified, making all values valid.</p>
<p><strong>Conclusion:</strong> All features passed range validation. The data set is free from unrealistic or invalid numeric entries and can be safely used for further analysis and modeling without further correction.</p>
</section>
</section>
<section id="statistical-summary" class="level2">
<h2 class="anchored" data-anchor-id="statistical-summary">3.Statistical Summary</h2>
<p>table summary of the key descriptive statistics for both datasets (<code>public_cases</code> and <code>private_cases</code>).</p>
<section id="statistical-summary-for-public-cases" class="level3">
<h3 class="anchored" data-anchor-id="statistical-summary-for-public-cases">Statistical Summary for Public Cases</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Statistic</th>
<th style="text-align: right;">trip_duration_days</th>
<th style="text-align: right;">miles_traveled</th>
<th style="text-align: right;">total_receipts_amount</th>
<th style="text-align: right;">expected_output</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>count</td>
<td style="text-align: right;">1000.000000</td>
<td style="text-align: right;">1000.00000</td>
<td style="text-align: right;">1000.00000</td>
<td style="text-align: right;">1000.000000</td>
</tr>
<tr class="even">
<td>mean</td>
<td style="text-align: right;">7.043000</td>
<td style="text-align: right;">597.41374</td>
<td style="text-align: right;">1211.05687</td>
<td style="text-align: right;">1349.114030</td>
</tr>
<tr class="odd">
<td>std</td>
<td style="text-align: right;">3.926139</td>
<td style="text-align: right;">351.29979</td>
<td style="text-align: right;">742.85418</td>
<td style="text-align: right;">470.316464</td>
</tr>
<tr class="even">
<td>min</td>
<td style="text-align: right;">1.000000</td>
<td style="text-align: right;">5.00000</td>
<td style="text-align: right;">1.42000</td>
<td style="text-align: right;">117.240000</td>
</tr>
<tr class="odd">
<td>25%</td>
<td style="text-align: right;">4.000000</td>
<td style="text-align: right;">275.96000</td>
<td style="text-align: right;">530.37750</td>
<td style="text-align: right;">1019.297500</td>
</tr>
<tr class="even">
<td>50%</td>
<td style="text-align: right;">7.000000</td>
<td style="text-align: right;">621.00000</td>
<td style="text-align: right;">1171.90000</td>
<td style="text-align: right;">1454.260000</td>
</tr>
<tr class="odd">
<td>75%</td>
<td style="text-align: right;">10.000000</td>
<td style="text-align: right;">893.00000</td>
<td style="text-align: right;">1881.10500</td>
<td style="text-align: right;">1711.122500</td>
</tr>
<tr class="even">
<td>max</td>
<td style="text-align: right;">14.000000</td>
<td style="text-align: right;">1317.07000</td>
<td style="text-align: right;">2503.46000</td>
<td style="text-align: right;">2337.730000</td>
</tr>
</tbody>
</table>
</section>
<section id="statistical-summary-for-private-cases" class="level3">
<h3 class="anchored" data-anchor-id="statistical-summary-for-private-cases">Statistical Summary for Private Cases</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 15%">
<col style="width: 28%">
<col style="width: 22%">
<col style="width: 32%">
</colgroup>
<thead>
<tr class="header">
<th>Statistic</th>
<th style="text-align: right;">trip_duration_days</th>
<th style="text-align: right;">miles_traveled</th>
<th style="text-align: right;">total_receipts_amount</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>count</td>
<td style="text-align: right;">5000.000000</td>
<td style="text-align: right;">5000.000000</td>
<td style="text-align: right;">5000.000000</td>
</tr>
<tr class="even">
<td>mean</td>
<td style="text-align: right;">7.199800</td>
<td style="text-align: right;">589.076406</td>
<td style="text-align: right;">1186.129164</td>
</tr>
<tr class="odd">
<td>std</td>
<td style="text-align: right;">3.998034</td>
<td style="text-align: right;">346.673720</td>
<td style="text-align: right;">719.695557</td>
</tr>
<tr class="even">
<td>min</td>
<td style="text-align: right;">1.000000</td>
<td style="text-align: right;">5.000000</td>
<td style="text-align: right;">0.270000</td>
</tr>
<tr class="odd">
<td>25%</td>
<td style="text-align: right;">4.000000</td>
<td style="text-align: right;">281.000000</td>
<td style="text-align: right;">567.845000</td>
</tr>
<tr class="even">
<td>50%</td>
<td style="text-align: right;">7.000000</td>
<td style="text-align: right;">588.000000</td>
<td style="text-align: right;">1154.810000</td>
</tr>
<tr class="odd">
<td>75%</td>
<td style="text-align: right;">11.000000</td>
<td style="text-align: right;">886.000000</td>
<td style="text-align: right;">1796.487500</td>
</tr>
<tr class="even">
<td>max</td>
<td style="text-align: right;">14.000000</td>
<td style="text-align: right;">1348.590000</td>
<td style="text-align: right;">2502.710000</td>
</tr>
</tbody>
</table>
</section>
<section id="statistical-summary-for-combined-datasets" class="level3">
<h3 class="anchored" data-anchor-id="statistical-summary-for-combined-datasets">Statistical Summary for Combined Datasets</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Statistic</th>
<th style="text-align: right;">trip_duration_days</th>
<th style="text-align: right;">miles_traveled</th>
<th style="text-align: right;">total_receipts_amount</th>
<th style="text-align: right;">reimbursement</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>count</td>
<td style="text-align: right;">6000.000000</td>
<td style="text-align: right;">6000.000000</td>
<td style="text-align: right;">6000.000000</td>
<td style="text-align: right;">1000.000000</td>
</tr>
<tr class="even">
<td>mean</td>
<td style="text-align: right;">7.173667</td>
<td style="text-align: right;">590.465962</td>
<td style="text-align: right;">1190.283782</td>
<td style="text-align: right;">1349.114030</td>
</tr>
<tr class="odd">
<td>std</td>
<td style="text-align: right;">3.986246</td>
<td style="text-align: right;">347.433429</td>
<td style="text-align: right;">723.603533</td>
<td style="text-align: right;">470.316464</td>
</tr>
<tr class="even">
<td>min</td>
<td style="text-align: right;">1.000000</td>
<td style="text-align: right;">5.000000</td>
<td style="text-align: right;">0.270000</td>
<td style="text-align: right;">117.240000</td>
</tr>
<tr class="odd">
<td>25%</td>
<td style="text-align: right;">4.000000</td>
<td style="text-align: right;">280.645000</td>
<td style="text-align: right;">561.285000</td>
<td style="text-align: right;">1019.297500</td>
</tr>
<tr class="even">
<td>50%</td>
<td style="text-align: right;">7.000000</td>
<td style="text-align: right;">594.500000</td>
<td style="text-align: right;">1157.310000</td>
<td style="text-align: right;">1454.260000</td>
</tr>
<tr class="odd">
<td>75%</td>
<td style="text-align: right;">11.000000</td>
<td style="text-align: right;">888.000000</td>
<td style="text-align: right;">1810.312500</td>
<td style="text-align: right;">1711.122500</td>
</tr>
<tr class="even">
<td>max</td>
<td style="text-align: right;">14.000000</td>
<td style="text-align: right;">1348.590000</td>
<td style="text-align: right;">2503.460000</td>
<td style="text-align: right;">2337.730000</td>
</tr>
</tbody>
</table>
<p><strong>Interpretation:</strong></p>
<p>Across individual public, private, and combined datasets, the overall trip characteristics remain consistent. The average trip duration is approximately 7 days, with trips ranging from 1 to 14 days. The average distance traveled is around 590 miles, indicating a mix of both short and long-distance trips. The mean total receipts amount is about $1,200, though the large spread and right-skewed distribution suggest a few high-cost trips influence the averages.</p>
<p>Both public and private cases exhibit nearly identical behavior in duration, distance, and total receipts, suggesting similar travel patterns or cost structures between the two groups. In public cases, the expected output average ($1,349) slightly exceeds the total receipts, indicating that projected reimbursements or returns are generally higher than actual costs.</p>
<p>In the combined dataset, overall patterns remain stable, confirming no major disparities between public and private cases. However, the reimbursement column is largely incomplete, with data available for only about 17% of all records. To address this, the next stage of analysis will focus on predicting the missing reimbursement values using a linear model based on observed relationships between data features. This will allow for a more complete and accurate assessment of the dataset.</p>
</section>
</section>
<section id="plotsvisuals" class="level2">
<h2 class="anchored" data-anchor-id="plotsvisuals">4.Plots/Visuals</h2>
<p><img src="images/clipboard-2283216152.png" width="536" height="324"></p>
<p><img src="images/clipboard-1342623851.png" class="img-fluid"></p>
<p><img src="images/clipboard-1097483454.png" class="img-fluid"></p>
<p><img src="images/clipboard-1448042906.png" class="img-fluid"></p>
<p><img src="images/clipboard-2854092379.png" class="img-fluid"></p>
<p><img src="images/clipboard-273174691.png" class="img-fluid"></p>
<p><img src="images/clipboard-4173228739.png" class="img-fluid"></p>
<p><img src="images/clipboard-899301835.png" class="img-fluid"></p>
<p><strong>Insights</strong></p>
<pre><code>- Receipts and miles traveled show strong positive correlation with reimbursement. 
- Trip duration contributes moderately, suggesting longer trips increase payouts.
- Data quality: No missing or invalid values detected.
- Both datasets are consistent in range and pattern.</code></pre>
</section>
<section id="outliers-or-anomaly-check" class="level2">
<h2 class="anchored" data-anchor-id="outliers-or-anomaly-check">5. Outliers or Anomaly Check</h2>
<p>None. Outliers were checked using the IQR (Interquartile Range) and none were detected.</p>
<p><strong>Results for Checking Outliers Using IQR</strong></p>
<section id="outlier-summary-public-cases" class="level3">
<h3 class="anchored" data-anchor-id="outlier-summary-public-cases">Outlier Summary (Public Cases)</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 32%">
<col style="width: 18%">
<col style="width: 18%">
<col style="width: 14%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>feature</th>
<th>lower_bound</th>
<th>upper_bound</th>
<th>outliers</th>
<th>outlier_%</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>trip_duration_days</td>
<td>-5.00000</td>
<td>19.00000</td>
<td>0</td>
<td>0.0</td>
</tr>
<tr class="even">
<td>miles_traveled</td>
<td>-649.60000</td>
<td>1818.56000</td>
<td>0</td>
<td>0.0</td>
</tr>
<tr class="odd">
<td>total_receipts_amount</td>
<td>-1495.71375</td>
<td>3907.19625</td>
<td>0</td>
<td>0.0</td>
</tr>
<tr class="even">
<td>expected_output</td>
<td>-18.44000</td>
<td>2748.86000</td>
<td>0</td>
<td>0.0</td>
</tr>
</tbody>
</table>
</section>
<section id="outlier-summary-private-cases" class="level3">
<h3 class="anchored" data-anchor-id="outlier-summary-private-cases">Outlier Summary (Private Cases)</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 32%">
<col style="width: 18%">
<col style="width: 18%">
<col style="width: 14%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>feature</th>
<th>lower_bound</th>
<th>upper_bound</th>
<th>outliers</th>
<th>outlier_%</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>trip_duration_days</td>
<td>-6.50000</td>
<td>21.50000</td>
<td>0</td>
<td>0.0</td>
</tr>
<tr class="even">
<td>miles_traveled</td>
<td>-626.50000</td>
<td>1793.50000</td>
<td>0</td>
<td>0.0</td>
</tr>
<tr class="odd">
<td>total_receipts_amount</td>
<td>-1275.11875</td>
<td>3639.45125</td>
<td>0</td>
<td>0.0</td>
</tr>
</tbody>
</table>
<p>We applied the <strong>Standard 1.5 × IQRmethod</strong> to identify potential outliers in the following numeric variables:</p>
<ul>
<li><code>trip_duration_days</code><br>
</li>
<li><code>miles_traveled</code><br>
</li>
<li><code>total_receipts_amount</code><br>
</li>
<li><code>expected_output</code> this is interchangeably referred to as reimbursement</li>
</ul>
<p><strong>Result/Interpretation:</strong><br>
No values were found outside the 1.5 × IQR range in either the public or private datasets.<br>
This indicates that the data is statistically consistent, with no extreme or anomalous values influencing the distributions.<br>
Overall, the numeric features appear well-behaved and suitable for further analysis.</p>
</section>
</section>
<section id="feature-exploration-data-summary" class="level2">
<h2 class="anchored" data-anchor-id="feature-exploration-data-summary">6. Feature Exploration Data Summary</h2>
<section id="trip-duration-days" class="level3">
<h3 class="anchored" data-anchor-id="trip-duration-days">Trip Duration (Days)</h3>
<ul>
<li><strong>Type:</strong> Numeric (integer)<br>
</li>
<li><strong>Distribution:</strong> Slight right skew — most trips range between 1 to 5 days.<br>
</li>
<li><strong>Correlation:</strong> Moderate positive correlation (~0.45) with reimbursement.<br>
</li>
<li><strong>Insight:</strong> Longer trips generally increase reimbursement due to additional lodging and meal expenses, but the effect tapers after a week.</li>
</ul>
<hr>
</section>
<section id="miles-traveled" class="level3">
<h3 class="anchored" data-anchor-id="miles-traveled">Miles Traveled</h3>
<ul>
<li><strong>Type:</strong> Numeric (integer)<br>
</li>
<li><strong>Distribution:</strong> Right-skewed, most travel occurs under 500 miles.<br>
</li>
<li><strong>Correlation:</strong> Strong positive correlation (~0.80) with reimbursement.<br>
</li>
<li><strong>Insight:</strong> Mileage is a major cost driver, showing nearly linear growth in payout with distance traveled.</li>
</ul>
<hr>
</section>
<section id="total-receipts-amount" class="level3">
<h3 class="anchored" data-anchor-id="total-receipts-amount">Total Receipts Amount</h3>
<ul>
<li><strong>Type:</strong> Numeric (float)<br>
</li>
<li><strong>Distribution:</strong> Positively skewed, with a few high-value cases but <em>no statistical outliers detected (IQR test)</em>.</li>
<li><strong>Correlation:</strong> Strongest correlation (~0.85) with reimbursement.<br>
</li>
<li><strong>Insight:</strong> Reflects direct trip costs such as accommodation and meals, highly predictive of total reimbursement.</li>
</ul>
<hr>
</section>
<section id="reimbursement-amount-target-variable" class="level3">
<h3 class="anchored" data-anchor-id="reimbursement-amount-target-variable">Reimbursement Amount (Target Variable)</h3>
<ul>
<li><strong>Type:</strong> Continuous numeric (float, rounded to 2 decimals)<br>
</li>
<li><strong>Distribution:</strong> Continuous, slightly right-skewed with some large but valid reimbursements — <em>no statistical outliers found</em>.<br>
</li>
<li><strong>Relationships:</strong>
<ul>
<li>Strong link to <strong>total receipts</strong> and <strong>miles traveled</strong><br>
</li>
<li>Moderate link to <strong>trip duration</strong><br>
</li>
</ul></li>
<li><strong>Insight:</strong> Represents the total predicted payout, primarily influenced by miles traveled and total receipts.<br>
Reimbursement can be effectively predicted using a <strong>linear model</strong> based on these three input variables.</li>
</ul>
<hr>
</section>
<section id="public-vs.-private-data-comparison" class="level3">
<h3 class="anchored" data-anchor-id="public-vs.-private-data-comparison">Public vs.&nbsp;Private Data Comparison</h3>
<ul>
<li><strong>Patterns:</strong> Both datasets follow similar trends and ranges.<br>
</li>
<li><strong>Variance:</strong> Slightly higher variance in private data, suggesting more diverse travel conditions.<br>
</li>
<li><strong>Consistency:</strong> Alignment in feature patterns confirms data reliability and shared underlying logic.</li>
</ul>
<hr>
</section>
<section id="overall-data-insights" class="level3">
<h3 class="anchored" data-anchor-id="overall-data-insights">Overall Data Insights</h3>
<ul>
<li><strong>Receipts</strong> and <strong>miles traveled</strong> are the dominant predictors of reimbursement.<br>
</li>
<li><strong>Trip duration</strong> adds context but shows a diminishing effect on reimbursement for longer trips.<br>
</li>
<li>No missing data or invalid records were detected, confirming <strong>high data integrity</strong>.<br>
</li>
<li>No statistical outliers were identified in either the public or private datasets, indicating that the data is <strong>consistent, well-distributed, and free from extreme or anomalous values</strong>.<br>
Such uniformity suggests <strong>high data quality</strong>, likely because the dataset was synthetically generated to simulate realistic yet controlled travel reimbursement patterns.<br>
This also supports the <strong>modeling phase</strong>, ensuring that no abnormal records will skew regression or classification outcomes.<br>
</li>
<li>Both datasets demonstrate <strong>consistent behavior</strong>, validating the model’s robustness across environments.</li>
</ul>
</section>
</section>
<section id="workup-and-code-sources" class="level2">
<h2 class="anchored" data-anchor-id="workup-and-code-sources">7. Workup and Code Sources</h2>
<p>The quality of the dataset is assessed in terms of missing values, validation, and outlier detection in a jupyter notebook. To recreate and observe the workup, access it here:</p>
<p>(<a href="https://github.com/MHaynes33/BlackBox/blob/main/Notebooks/week1_data_cleaning.ipynb" class="uri">https://github.com/MHaynes33/BlackBox/blob/main/Notebooks/week1_data_cleaning.ipynb</a>.</p>
<p>Further exploration of the data involving statistical summary and visualization through plots for the combined data, assessment of dataset relationships, and data features were observed and processed through a jupyter notebook. To recreate and observe the workup, access it here:</p>
<p>(<a href="https://github.com/MHaynes33/BlackBox/blob/main/Notebooks/01_EDA_Reimbursement%20(3).ipynb" class="uri">https://github.com/MHaynes33/BlackBox/blob/main/Notebooks/01_EDA_Reimbursement%20(3).ipynb</a>.</p>
<hr>
</section>
<section id="baseline-model" class="level2">
<h2 class="anchored" data-anchor-id="baseline-model">8. Baseline Model</h2>
<section id="name-acme-reimbursement-baseline-v1" class="level3">
<h3 class="anchored" data-anchor-id="name-acme-reimbursement-baseline-v1">Name: ACME Reimbursement Baseline (v1)</h3>
<p><strong>Objective</strong></p>
<p>Establish a benchmark model for predicting reimbursement amounts using the cleaned public_cases dataset. The aim is to evaluate how well we could capture relationships among trip duration, mileage, and total receipts using the baseline model before implementing more complex ensemble models in later phases.</p>
</section>
<section id="the-process" class="level3">
<h3 class="anchored" data-anchor-id="the-process"><strong>The Process</strong></h3>
<section id="derived-features" class="level4">
<h4 class="anchored" data-anchor-id="derived-features">Derived Features</h4>
<dl>
<dt>To enhance interpretability and capture travel-cost dynamics, several derived variables were engineered:</dt>
<dd>
<p>Cost per Day = total_receipts_amount / trip_duration_days -&gt; measures daily travel expense</p>
</dd>
<dd>
<p>Cost per Mile = total_receipts_amount / miles_traveled -&gt; measures efficiency per mile</p>
</dd>
<dd>
<p>Miles per Day = miles_traveled / trip_duration_days -&gt; captures travel intensity</p>
</dd>
<dd>
<p>Cost Ratio = cost_per_day / cost_per_mile -&gt; reflects spending efficiency balance</p>
</dd>
</dl>
<p>These variables reflect efficiency and expense intensity for each trip, helping replicate hidden business logic from the legacy system.</p>
<p>An IQR-based outlier check confirmed data stability, with most outliers found only in derived ratios (≈ 100 cases each).</p>
<p><strong>Feature Distribution</strong></p>
<p><img src="images/clipboard-1593421446.png" class="img-fluid"></p>
<p><strong>Interpretation</strong></p>
<dl>
<dt>The histograms illustrate that:</dt>
<dd>
<p>Most trips cluster at low or moderate costs.</p>
</dd>
<dd>
<p>A few longer trips with high receipts cause right-skewed tails.</p>
</dd>
<dd>
<p>All derived metrics are positive and consistent which means that no missing or invalid values remain.</p>
</dd>
</dl>
<p>Insight: Cost-related distributions show expected business behavior — short trips dominate, while extended ones increase receipts and reimbursement amounts.</p>
</section>
<section id="modeling-setup-and-baseline-model-results" class="level4">
<h4 class="anchored" data-anchor-id="modeling-setup-and-baseline-model-results">Modeling Setup and Baseline Model Results</h4>
<p><strong>Features used:</strong> <code>trip_duration_days</code>, <code>miles_traveled</code>, <code>total_receipts_amount</code>, <code>cost_per_day</code>, <code>cost_per_mile</code>, <code>miles_per_day</code>, <code>cost_ratio</code></p>
<p><strong>Target:</strong> <code>reimbursement</code></p>
<p><strong>Train/Test Split:</strong> 75 % of the data used for training and 25 % for testing to maintain reproducibility.</p>
<p><strong>Evaluation Metrics:</strong> R² (coefficient of determination), RMSE (root mean squared error), MAE (mean absolute error)</p>
<p>The baseline modeling stage compared four regression algorithms to predict reimbursement: <strong>Linear Regression</strong>, <strong>Ridge Regression</strong>, <strong>Lasso Regression</strong>, and <strong>Polynomial Regression (degree = 2)</strong>.</p>
<p>Summary for the baseline mode</p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Model</th>
<th style="text-align: center;">R² Score</th>
<th style="text-align: center;">RMSE</th>
<th style="text-align: center;">MAE</th>
<th style="text-align: left;">Key Interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Linear Regression</strong></td>
<td style="text-align: center;"><strong>0.784</strong></td>
<td style="text-align: center;"><strong>199.85</strong></td>
<td style="text-align: center;"><strong>159.59</strong></td>
<td style="text-align: left;">Strong baseline fit; captures linear cost–distance relationships</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Ridge Regression (α = 1.0)</strong></td>
<td style="text-align: center;">0.784</td>
<td style="text-align: center;">199.84</td>
<td style="text-align: center;">—</td>
<td style="text-align: left;">Similar performance; adds coefficient stability</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Lasso Regression (α = 0.01)</strong></td>
<td style="text-align: center;">0.784</td>
<td style="text-align: center;">199.85</td>
<td style="text-align: center;">—</td>
<td style="text-align: left;">Similar accuracy; produces a more compact model</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Polynomial Regression (deg = 2)</strong></td>
<td style="text-align: center;"><strong>0.892</strong></td>
<td style="text-align: center;"><strong>141.64</strong></td>
<td style="text-align: center;">—</td>
<td style="text-align: left;">Captures nonlinear relationships between trip variables</td>
</tr>
</tbody>
</table>
</section>
<section id="what-these-evaluation-metrics-mean" class="level4">
<h4 class="anchored" data-anchor-id="what-these-evaluation-metrics-mean"><strong>What these evaluation metrics mean:</strong></h4>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Metric</strong></th>
<th style="text-align: left;"><strong>What It Measures</strong></th>
<th style="text-align: left;"><strong>Why It Matters in This Project</strong></th>
<th style="text-align: left;"><strong>Result</strong></th>
<th style="text-align: left;"><strong>Interpretation</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>MAE (Mean Absolute Error)</strong></td>
<td style="text-align: left;">Average difference (in dollars or cents) between the model and legacy output</td>
<td style="text-align: left;">Shows typical deviation — lower MAE means closer day-to-day matching</td>
<td style="text-align: left;">X.XX ¢</td>
<td style="text-align: left;">A small MAE indicates the model captures core reimbursement patterns well.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>RMSE (Root Mean Squared Error)</strong></td>
<td style="text-align: left;">Penalizes larger errors more heavily</td>
<td style="text-align: left;">Reveals if a few cases are significantly off due to threshold or rounding effects</td>
<td style="text-align: left;">X.XX ¢</td>
<td style="text-align: left;">A low RMSE suggests no large outlier mismatches; a high RMSE suggests missing rules or quirks.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Accuracy within ± $1</strong></td>
<td style="text-align: left;">% of cases where predicted reimbursement is within $1.00 of the legacy output</td>
<td style="text-align: left;">Measures practical similarity even if not exact</td>
<td style="text-align: left;">XX.X %</td>
<td style="text-align: left;">High accuracy here means the model approximates behavior well, even if exact-match logic needs refinement.</td>
</tr>
</tbody>
</table>
<hr>
</section>
<section id="interpretation-guidelines" class="level4">
<h4 class="anchored" data-anchor-id="interpretation-guidelines">Interpretation Guidelines</h4>
<ul>
<li><p><strong>If MAE is low but RMSE is high:</strong><br>
→ The model performs well on most cases but fails in specific threshold regions.</p></li>
<li><p><strong>If both MAE and RMSE are low but exact-match rate is below target:</strong><br>
→ The model’s math logic is correct, but rounding or step-function rules may still need tuning.</p></li>
<li><p><strong>If Accuracy within ± $1 is high but EMR is low:</strong><br>
→ The model’s behavior closely matches the legacy engine, but exact bitwise replication isn’t yet achieved — this is expected before incorporating fine-grained “quirk-capture” rules.</p></li>
</ul>
<hr>
</section>
<section id="interpretation-of-model-performance" class="level4">
<h4 class="anchored" data-anchor-id="interpretation-of-model-performance">Interpretation of Model Performance</h4>
<ul>
<li><p><strong>Linear Regression</strong> explains about <strong>78% of the variance</strong> in reimbursement values (R² = 0.784).<br>
The typical prediction error is roughly <strong>±$160</strong>, and most estimates fall within <strong>$200</strong> of the true amount.<br>
This indicates that simple linear relationships already describe most of the reimbursement behavior.</p></li>
<li><p><strong>Ridge and Lasso Regression</strong> yield identical R² scores.<br>
These regularization techniques penalize overly large coefficients, improving model <strong>stability</strong> and <strong>interpretability</strong>, even though predictive accuracy remains unchanged.<br>
Their similar results suggest <strong>no major multicollinearity</strong> or overfitting issues in the baseline data.</p></li>
<li><p><strong>Polynomial Regression (Degree = 2)</strong> significantly improves performance, raising R² from <strong>0.784 → 0.892</strong> and lowering RMSE from <strong>199.85 → 141.64</strong>.<br>
This improvement shows that <strong>nonlinear interactions</strong> (e.g., between trip duration and receipts or miles and cost ratios) play a key role in determining reimbursements.</p></li>
</ul>
<hr>
</section>
<section id="insights" class="level4">
<h4 class="anchored" data-anchor-id="insights">Insights</h4>
<ul>
<li><p><strong>Key Drivers:</strong> <code>total_receipts_amount</code> and <code>miles_traveled</code> contribute most to explaining reimbursement variation, while <code>trip_duration_days</code> adds modest context.</p></li>
<li><p><strong>Model Implications:</strong> The strong improvement from polynomial terms indicates that <strong>ACME’s legacy reimbursement system likely uses nonlinear logic</strong>, such as tiered rates or mileage thresholds.</p></li>
<li><p><strong>Error Analysis:</strong> The RMSE and MAE values are small relative to the mean reimbursement (~$1,300), suggesting a reliable predictive foundation.</p></li>
</ul>
<hr>
</section>
<section id="conclusion" class="level4">
<h4 class="anchored" data-anchor-id="conclusion">Conclusion</h4>
<p>The baseline models establish a solid benchmark for the ACME reimbursement prediction task.</p>
<p>Linear regression captures most linear cost patterns, while the polynomial model best replicates the <strong>nonlinear structure</strong> of the legacy reimbursement logic.</p>
<p><img src="images/clipboard-1576910411.png" class="img-fluid"></p>
<p>These results confirm the validity of the engineered features and provide a foundation for more advanced ensemble approaches (e.g., Random Forest or Gradient Boosting) in later phases.</p>
</section>
<section id="product-of-baseline-model" class="level4">
<h4 class="anchored" data-anchor-id="product-of-baseline-model">Product of Baseline Model</h4>
<p>Dataset saved: <a href="https://github.com/MHaynes33/BlackBox/blob/main/data/phase2_features_baseline_models.csv">Phase 2 Baseline Model Data</a></p>
<hr>
</section>
</section>
<section id="baseline-model-information-and-work-up-source" class="level3">
<h3 class="anchored" data-anchor-id="baseline-model-information-and-work-up-source">Baseline Model Information and Work up Source:</h3>
<p><a href="https://github.com/MHaynes33/BlackBox/blob/main/Notebooks/02_Feature_Engineering_and_Baseline_Model.ipynb" class="uri">https://github.com/MHaynes33/BlackBox/blob/main/Notebooks/02_Feature_Engineering_and_Baseline_Model.ipynb</a></p>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>